#!/opt/ipc/bin/php
<?php

/**
 * Requires dos2unix to be installed on the machine as well.
 */

class convertor
{
    private $_current_dir;
    private $_counter;

    public function dos2unix($orig_filename)
    {
        $current_dir = dirname($orig_filename);

        if ($current_dir != $this->_current_dir) {
            $this->_current_dir = $current_dir;
            print "Current Directory: {$current_dir}\n";
        }
        $command = "dos2unix {$orig_filename}";

        shell_exec($command);
    }

    public function getAllFiles()
    {
        return explode("\n", shell_exec('find . "')); // find all files...
    }

    public function execute()
    {
        $files = $this->getAllFiles();

        print "File Found: ".count($files)."\n";
        print "Beginning convertion...\n";

        foreach($files as $idx => $filename) {
            if (is_file($filename)) {
                if (preg_match('#.(css|php|js|yml|txt)$#i', $filename)) {
                    $this->dos2unix($filename);
                } else {
                    print "- '{$filename}' skipped.\n";
                }
            }
        }
    }
}

$convertor = new convertor();
$convertor->execute();
